// Copyright (c) 2021 Secure64 Software
// All Rights Reserved
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// * Neither the name of Secure64 Software nor the names of its contributors
//   may be used to endorse or promote products derived from this software
//   without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// ubc-man [ spec.xml ... ]
//
//	Extract the help information from the unbound control XML description
//	and put generate a troff source file to include in unbound-control.8

#include "ubc-xml.h"

static void
printOption(FILE *fp, const XML_Char *opt)
{
	XML_Char c;

	fprintf(fp, " \\fI");

	while ((c = *opt++) != '\0') {
		// For options, print [] and | as regular font

		if (c == '[' || c == ']' || c == '|') {
			fprintf(fp, "\\fR%c\\fI", c);
		} else {
			fprintf(fp, "%c", c);
		}
	}

	fprintf(fp, "\\fB");
}

void XMLCALL
xmlStart(void *udata, const XML_Char *name, const XML_Char **attrs)
{
	struct parser_data *pdp = udata;

	if (strcmp(name, "ManPage") == 0) {
		if (pdp->command == NULL) {
			parse_error(pdp, "Unexpected man page spec!");
			exit(1);
		}
			
		pdp->flags = 1;
	} else if (strcmp(name, "Command") == 0) {
		const XML_Char *key;

		// Start the decoration for the man page entry. If the first attribute
		// is "view", append the view qualifier. Note that we have to skip
		// the command="cmd-name" option

		fprintf(pdp->out, ".TP\n.B " XML_STR(""), pdp->command);

		attrs += 2;

		if ((key = attrs[0]) != NULL && strcmp(key, "view") == 0) {
			const XML_Char *val = attrs[1];
			attrs += 2;

			if (strcmp(val, "yes") == 0) {
				fprintf(pdp->out, "\\fR[\\fI.view\\fR]");
			} else if (strcmp(val, "no") != 0) {
				parse_error(pdp, "unknown value for view '" XML_STR(""), val);
				exit(1);
			}
		}

		// Process arguments, if any. The calling program has validated there
		// are a even number and provided the count for us.

		while ((key = *attrs++) != NULL) {
			printOption(pdp->out, *attrs++);
		}

		fprintf(pdp->out, "\n");
	} else if (strcmp(name, "CommandList") == 0) {
		static const char noarchive[] =
			".\\\" THIS FILE IS AUTOMATICALLY GENERATED\n"
			".\\\" DO NOT EDIT, MODIFY, COMMIT, ARCHIVE!\n"
			".\\\" LOOK AT smallapp/ubc.xml FOR MORE INFORMATION\n";

		fprintf(pdp->out, "%s", noarchive);
	}
}

void XMLCALL
xmlEnd(void *udata, const XML_Char *name)
{
	struct parser_data *pdp = udata;

	if (strcmp(name, "Command") == 0) {
		clrCommandInfo(pdp);
	} else if (strcmp(name, "ManPage") == 0) {
		pdp->flags = 0;
	}
}

void
xmlComment(void *udata, const XML_Char *info)
{
}

void
xmlText(void *udata, const XML_Char *info, int len)
{
	struct parser_data *pdp = udata;

	if (pdp->flags != 0) {
		do {
			fprintf(pdp->out, XML_STR("1.1"), info++);
		} while (len-- != 1);

		fprintf(pdp->out, "\n");
	}
}
