#!/bin/sh
#
# unbound freebsd startup rc.d script, modified from the named script.
# uses the default unbound installation path and pidfile location.
# copy this to /etc/rc.d/unbound
# and put unbound_enable="YES" into rc.conf
#

# PROVIDE: unbound
# REQUIRE: SERVERS cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="unbound"
rcvar=`set_rcvar`

command="/usr/local/sbin/unbound"
pidfile="/etc/unbound/unbound.pid"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
