// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT, MODIFY, COMMIT, ARCHIVE!
// LOOK AT smallapp/ubc.xml FOR MORE INFORMATION

struct cmd_info {
	char const *cmd;
	char const *info;
};

static void
helpList(void)
{
	static const struct cmd_info commandList[] = {
		{
			"start",
			"start server; runs unbound(8)"
		},
		{
			"stop",
			"stops the server"
		},
		{
			"echo",
			"echo command line arguments"
		},
		{
			"reload",
			"reloads the server"
		},
		{
			"",
			"(this flushes data, stats, requestlist)"
		},
		{
			"verbosity",
			"change logging detail"
		},
		{
			"log_reopen",
			"close and open the logfile"
		},
		{
			"stats",
			"print statistics"
		},
		{
			"stats_noreset",
			"peek at statistics"
		},
#if defined(HAVE_SHMGET)
		{
			"stats_shm",
			"print statistics using shm"
		},
#endif
		{
			"status",
			"display status of server"
		},
		{
			"local_zone",
			"add new local zone"
		},
		{
			"local_zone_remove",
			"remove local zone and its contents"
		},
		{
			"local_data",
			"add local data, for example"
		},
		{
			"",
			"local_data www.example.com A 192.0.2.1"
		},
		{
			"local_data_remove",
			"remove local RR data from name"
		},
		{
			"local_zones, local_zones_remove, local_datas, local_datas_remove",
			""
		},
		{
			"",
			"same, but read list from stdin"
		},
		{
			"",
			"(one entry per line)."
		},
		{
			"dump_cache",
			"print cache to stdout"
		},
		{
			"load_cache",
			"load cache from stdin"
		},
		{
			"lookup",
			"print nameservers for name"
		},
		{
			"flush",
			"flushes common types for name from cache"
		},
		{
			"",
			"types:  A, AAAA, MX, PTR, NS,"
		},
		{
			"",
			"SOA, CNAME, DNAME, SRV, NAPTR"
		},
		{
			"flush_type",
			"flush name, type from cache"
		},
		{
			"flush_zone",
			"flush everything at or under name"
		},
		{
			"",
			"from rr and dnssec caches"
		},
		{
			"flush_bogus",
			"flush all bogus data"
		},
		{
			"flush_negative",
			"flush all negative data"
		},
		{
			"flush_stats",
			"flush statistics, make zerp"
		},
		{
			"flush_requestlist",
			"drop queries that are worked on"
		},
		{
			"dump_requestlist",
			"show what is worked on by first thread"
		},
		{
			"flush_infra",
			"remove ping, edns for one IP or all"
		},
		{
			"dump_infra",
			"show RTT and edns entries"
		},
		{
			"set_option",
			"set option to value, no reload"
		},
		{
			"get_option",
			"get option value"
		},
		{
			"list_stubs",
			"list stub-zones and root hints in use"
		},
		{
			"list_forwards",
			"list forward-zones in use"
		},
		{
			"list_insecure",
			"list domain-insecure zones"
		},
		{
			"list_local_zones",
			"list local-zones in use"
		},
		{
			"list_local_data",
			"list local-data RRs in use"
		},
		{
			"list_views",
			"list configured views"
		},
		{
			"insecure_add",
			"add domain-insecure zone"
		},
		{
			"insecure_remove",
			"remove domain-insecure zone"
		},
		{
			"ratelimit_list",
			"list ratelimited domains"
		},
		{
			"",
			"+a  list all, also not ratelimited"
		},
		{
			"ip_ratelimit_list",
			"list ratelimited ip addresses"
		},
		{
			"",
			"+a  list all, also not ratelimited"
		},
		{
			"list_auth_zones",
			"list auth zones"
		},
		{
			"auth_zone_reload",
			"reload auth zone from zonefile"
		},
		{
			"auth_zone_transfer",
			"transfer auth zone from master"
		},
		{
			"rpz_enable",
			"Enable the RPZ zone if it had previously"
		},
		{
			"",
			"been disabled"
		},
		{
			"rpz_disable",
			"Disable the RPZ zone"
		},
		{
			"view_list_local_zones",
			"synonym for list_local_zones.view-name"
		},
		{
			"view_local_zone",
			"synonym for local_zone.view-name"
		},
		{
			"view_local_zone_remove",
			"synonym for local_zone_remove.view-name"
		},
		{
			"view_list_local_data",
			"synonym for list_local_data.view-name"
		},
		{
			"view_local_data",
			"synonym for local_data.view-name"
		},
		{
			"view_local_data_remove",
			"synonym for local_data_remove.view-name"
		},
		{
			"view_local_datas",
			"synonym for local_datas.view-name"
		},
		{
			"view_local_datas_remove",
			"synonym for local_datas_remove.view-name"
		},
		{ NULL, NULL }
	};

	struct cmd_info const *cip = commandList;
	char const *cmd;

	while ((cmd = cip->cmd) != NULL) {
		printf("  %-26s%s\n",
		       cmd,
		       cip->info);
		cip++;
	}
}
