.\"
.\" unbound.8 -- unbound manual
.\"
.\" Copyright (c) 2007, NLnet Labs. All rights reserved.
.\"
.\" See LICENSE for the license.
.\"
.\"
.Dd @date@
.Dt unbound 8
.Sh NAME
unbound
.Nd Unbound DNS validating resolver @version@.
.Sh SYNOPSIS
.Nm unbound
.Op Fl h
.Op Fl d
.Op Fl v
.Op Fl C
.Op Fl c Ar cfgfile

.Sh DESCRIPTION
.Ic Unbound 
is an implementation of a DNS resolver, that does caching and 
DNSSEC validation.
.Pp
The available options are:
.Bl -tag -width indent

.It Fl h
Show the version and commandline option help.

.It Fl c Ar cfgfile
Set the config file to read with settings for unbound. The syntax is
described in 
.Xr unbound.conf 5 .

.It Fl d
Debug flag, do not fork into the background, but stay attached to the
console.

.It Fl v
Increase verbosity. If given multiple times, more information is logged.
This is in addition to the verbosity (if any) from the config file.

.It Fl C
Try to enable coredumps after forking into the background. If you do not
have permission to alter the ulimits, then this will fail. Performs
the equivalent of 'ulimit -c unlimited'. For debug purposes.

.El
.Sh SEE ALSO
.Xr unbound.conf 5 .

.Sh AUTHORS
.Ic Unbound
developers are mentioned in the CREDITS file in the distribution.
