/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_YY_UTIL_CONFIGPARSER_H_INCLUDED
# define YY_YY_UTIL_CONFIGPARSER_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    YYEOF = 0,                     /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    SPACE = 258,                   /* SPACE  */
    LETTER = 259,                  /* LETTER  */
    NEWLINE = 260,                 /* NEWLINE  */
    COMMENT = 261,                 /* COMMENT  */
    COLON = 262,                   /* COLON  */
    ANY = 263,                     /* ANY  */
    ZONESTR = 264,                 /* ZONESTR  */
    STRING_ARG = 265,              /* STRING_ARG  */
    VAR_FORCE_TOPLEVEL = 266,      /* VAR_FORCE_TOPLEVEL  */
    VAR_SERVER = 267,              /* VAR_SERVER  */
    VAR_VERBOSITY = 268,           /* VAR_VERBOSITY  */
    VAR_NUM_THREADS = 269,         /* VAR_NUM_THREADS  */
    VAR_PORT = 270,                /* VAR_PORT  */
    VAR_OUTGOING_RANGE = 271,      /* VAR_OUTGOING_RANGE  */
    VAR_INTERFACE = 272,           /* VAR_INTERFACE  */
    VAR_PREFER_IP4 = 273,          /* VAR_PREFER_IP4  */
    VAR_DO_IP4 = 274,              /* VAR_DO_IP4  */
    VAR_DO_IP6 = 275,              /* VAR_DO_IP6  */
    VAR_PREFER_IP6 = 276,          /* VAR_PREFER_IP6  */
    VAR_DO_UDP = 277,              /* VAR_DO_UDP  */
    VAR_DO_TCP = 278,              /* VAR_DO_TCP  */
    VAR_TCP_MSS = 279,             /* VAR_TCP_MSS  */
    VAR_OUTGOING_TCP_MSS = 280,    /* VAR_OUTGOING_TCP_MSS  */
    VAR_TCP_IDLE_TIMEOUT = 281,    /* VAR_TCP_IDLE_TIMEOUT  */
    VAR_EDNS_TCP_KEEPALIVE = 282,  /* VAR_EDNS_TCP_KEEPALIVE  */
    VAR_EDNS_TCP_KEEPALIVE_TIMEOUT = 283, /* VAR_EDNS_TCP_KEEPALIVE_TIMEOUT  */
    VAR_CHROOT = 284,              /* VAR_CHROOT  */
    VAR_USERNAME = 285,            /* VAR_USERNAME  */
    VAR_DIRECTORY = 286,           /* VAR_DIRECTORY  */
    VAR_LOGFILE = 287,             /* VAR_LOGFILE  */
    VAR_PIDFILE = 288,             /* VAR_PIDFILE  */
    VAR_AZONE_IO_THREAD = 289,     /* VAR_AZONE_IO_THREAD  */
    VAR_MSG_CACHE_SIZE = 290,      /* VAR_MSG_CACHE_SIZE  */
    VAR_MSG_CACHE_SLABS = 291,     /* VAR_MSG_CACHE_SLABS  */
    VAR_NUM_QUERIES_PER_THREAD = 292, /* VAR_NUM_QUERIES_PER_THREAD  */
    VAR_RRSET_CACHE_SIZE = 293,    /* VAR_RRSET_CACHE_SIZE  */
    VAR_RRSET_CACHE_SLABS = 294,   /* VAR_RRSET_CACHE_SLABS  */
    VAR_OUTGOING_NUM_TCP = 295,    /* VAR_OUTGOING_NUM_TCP  */
    VAR_INFRA_HOST_TTL = 296,      /* VAR_INFRA_HOST_TTL  */
    VAR_INFRA_LAME_TTL = 297,      /* VAR_INFRA_LAME_TTL  */
    VAR_INFRA_CACHE_SLABS = 298,   /* VAR_INFRA_CACHE_SLABS  */
    VAR_INFRA_CACHE_NUMHOSTS = 299, /* VAR_INFRA_CACHE_NUMHOSTS  */
    VAR_INFRA_CACHE_LAME_SIZE = 300, /* VAR_INFRA_CACHE_LAME_SIZE  */
    VAR_NAME = 301,                /* VAR_NAME  */
    VAR_STUB_ZONE = 302,           /* VAR_STUB_ZONE  */
    VAR_STUB_HOST = 303,           /* VAR_STUB_HOST  */
    VAR_STUB_ADDR = 304,           /* VAR_STUB_ADDR  */
    VAR_TARGET_FETCH_POLICY = 305, /* VAR_TARGET_FETCH_POLICY  */
    VAR_HARDEN_SHORT_BUFSIZE = 306, /* VAR_HARDEN_SHORT_BUFSIZE  */
    VAR_HARDEN_LARGE_QUERIES = 307, /* VAR_HARDEN_LARGE_QUERIES  */
    VAR_FORWARD_ZONE = 308,        /* VAR_FORWARD_ZONE  */
    VAR_FORWARD_HOST = 309,        /* VAR_FORWARD_HOST  */
    VAR_FORWARD_ADDR = 310,        /* VAR_FORWARD_ADDR  */
    VAR_DO_NOT_QUERY_ADDRESS = 311, /* VAR_DO_NOT_QUERY_ADDRESS  */
    VAR_HIDE_IDENTITY = 312,       /* VAR_HIDE_IDENTITY  */
    VAR_HIDE_VERSION = 313,        /* VAR_HIDE_VERSION  */
    VAR_IDENTITY = 314,            /* VAR_IDENTITY  */
    VAR_VERSION = 315,             /* VAR_VERSION  */
    VAR_HARDEN_GLUE = 316,         /* VAR_HARDEN_GLUE  */
    VAR_MODULE_CONF = 317,         /* VAR_MODULE_CONF  */
    VAR_TRUST_ANCHOR_FILE = 318,   /* VAR_TRUST_ANCHOR_FILE  */
    VAR_TRUST_ANCHOR = 319,        /* VAR_TRUST_ANCHOR  */
    VAR_VAL_OVERRIDE_DATE = 320,   /* VAR_VAL_OVERRIDE_DATE  */
    VAR_BOGUS_TTL = 321,           /* VAR_BOGUS_TTL  */
    VAR_VAL_CLEAN_ADDITIONAL = 322, /* VAR_VAL_CLEAN_ADDITIONAL  */
    VAR_VAL_PERMISSIVE_MODE = 323, /* VAR_VAL_PERMISSIVE_MODE  */
    VAR_INCOMING_NUM_TCP = 324,    /* VAR_INCOMING_NUM_TCP  */
    VAR_MSG_BUFFER_SIZE = 325,     /* VAR_MSG_BUFFER_SIZE  */
    VAR_KEY_CACHE_SIZE = 326,      /* VAR_KEY_CACHE_SIZE  */
    VAR_KEY_CACHE_SLABS = 327,     /* VAR_KEY_CACHE_SLABS  */
    VAR_TRUSTED_KEYS_FILE = 328,   /* VAR_TRUSTED_KEYS_FILE  */
    VAR_VAL_NSEC3_KEYSIZE_ITERATIONS = 329, /* VAR_VAL_NSEC3_KEYSIZE_ITERATIONS  */
    VAR_USE_SYSLOG = 330,          /* VAR_USE_SYSLOG  */
    VAR_OUTGOING_INTERFACE = 331,  /* VAR_OUTGOING_INTERFACE  */
    VAR_ROOT_HINTS = 332,          /* VAR_ROOT_HINTS  */
    VAR_DO_NOT_QUERY_LOCALHOST = 333, /* VAR_DO_NOT_QUERY_LOCALHOST  */
    VAR_CACHE_MAX_TTL = 334,       /* VAR_CACHE_MAX_TTL  */
    VAR_HARDEN_DNSSEC_STRIPPED = 335, /* VAR_HARDEN_DNSSEC_STRIPPED  */
    VAR_ACCESS_CONTROL = 336,      /* VAR_ACCESS_CONTROL  */
    VAR_LOCAL_ZONE = 337,          /* VAR_LOCAL_ZONE  */
    VAR_LOCAL_DATA = 338,          /* VAR_LOCAL_DATA  */
    VAR_INTERFACE_AUTOMATIC = 339, /* VAR_INTERFACE_AUTOMATIC  */
    VAR_STATISTICS_INTERVAL = 340, /* VAR_STATISTICS_INTERVAL  */
    VAR_DO_DAEMONIZE = 341,        /* VAR_DO_DAEMONIZE  */
    VAR_USE_CAPS_FOR_ID = 342,     /* VAR_USE_CAPS_FOR_ID  */
    VAR_STATISTICS_CUMULATIVE = 343, /* VAR_STATISTICS_CUMULATIVE  */
    VAR_OUTGOING_PORT_PERMIT = 344, /* VAR_OUTGOING_PORT_PERMIT  */
    VAR_OUTGOING_PORT_AVOID = 345, /* VAR_OUTGOING_PORT_AVOID  */
    VAR_DLV_ANCHOR_FILE = 346,     /* VAR_DLV_ANCHOR_FILE  */
    VAR_DLV_ANCHOR = 347,          /* VAR_DLV_ANCHOR  */
    VAR_NEG_CACHE_SIZE = 348,      /* VAR_NEG_CACHE_SIZE  */
    VAR_HARDEN_REFERRAL_PATH = 349, /* VAR_HARDEN_REFERRAL_PATH  */
    VAR_PRIVATE_ADDRESS = 350,     /* VAR_PRIVATE_ADDRESS  */
    VAR_PRIVATE_DOMAIN = 351,      /* VAR_PRIVATE_DOMAIN  */
    VAR_REMOTE_CONTROL = 352,      /* VAR_REMOTE_CONTROL  */
    VAR_CONTROL_ENABLE = 353,      /* VAR_CONTROL_ENABLE  */
    VAR_CONTROL_INTERFACE = 354,   /* VAR_CONTROL_INTERFACE  */
    VAR_CONTROL_PORT = 355,        /* VAR_CONTROL_PORT  */
    VAR_SERVER_KEY_FILE = 356,     /* VAR_SERVER_KEY_FILE  */
    VAR_SERVER_CERT_FILE = 357,    /* VAR_SERVER_CERT_FILE  */
    VAR_CONTROL_KEY_FILE = 358,    /* VAR_CONTROL_KEY_FILE  */
    VAR_CONTROL_CERT_FILE = 359,   /* VAR_CONTROL_CERT_FILE  */
    VAR_CONTROL_USE_CERT = 360,    /* VAR_CONTROL_USE_CERT  */
    VAR_TCP_REUSE_TIMEOUT = 361,   /* VAR_TCP_REUSE_TIMEOUT  */
    VAR_MAX_REUSE_TCP_QUERIES = 362, /* VAR_MAX_REUSE_TCP_QUERIES  */
    VAR_EXTENDED_STATISTICS = 363, /* VAR_EXTENDED_STATISTICS  */
    VAR_LOCAL_DATA_PTR = 364,      /* VAR_LOCAL_DATA_PTR  */
    VAR_JOSTLE_TIMEOUT = 365,      /* VAR_JOSTLE_TIMEOUT  */
    VAR_STUB_PRIME = 366,          /* VAR_STUB_PRIME  */
    VAR_UNWANTED_REPLY_THRESHOLD = 367, /* VAR_UNWANTED_REPLY_THRESHOLD  */
    VAR_LOG_TIME_ASCII = 368,      /* VAR_LOG_TIME_ASCII  */
    VAR_DOMAIN_INSECURE = 369,     /* VAR_DOMAIN_INSECURE  */
    VAR_PYTHON = 370,              /* VAR_PYTHON  */
    VAR_PYTHON_SCRIPT = 371,       /* VAR_PYTHON_SCRIPT  */
    VAR_VAL_SIG_SKEW_MIN = 372,    /* VAR_VAL_SIG_SKEW_MIN  */
    VAR_VAL_SIG_SKEW_MAX = 373,    /* VAR_VAL_SIG_SKEW_MAX  */
    VAR_VAL_MAX_RESTART = 374,     /* VAR_VAL_MAX_RESTART  */
    VAR_CACHE_MIN_TTL = 375,       /* VAR_CACHE_MIN_TTL  */
    VAR_VAL_LOG_LEVEL = 376,       /* VAR_VAL_LOG_LEVEL  */
    VAR_AUTO_TRUST_ANCHOR_FILE = 377, /* VAR_AUTO_TRUST_ANCHOR_FILE  */
    VAR_KEEP_MISSING = 378,        /* VAR_KEEP_MISSING  */
    VAR_ADD_HOLDDOWN = 379,        /* VAR_ADD_HOLDDOWN  */
    VAR_DEL_HOLDDOWN = 380,        /* VAR_DEL_HOLDDOWN  */
    VAR_SO_RCVBUF = 381,           /* VAR_SO_RCVBUF  */
    VAR_EDNS_BUFFER_SIZE = 382,    /* VAR_EDNS_BUFFER_SIZE  */
    VAR_PREFETCH = 383,            /* VAR_PREFETCH  */
    VAR_PREFETCH_KEY = 384,        /* VAR_PREFETCH_KEY  */
    VAR_SO_SNDBUF = 385,           /* VAR_SO_SNDBUF  */
    VAR_SO_REUSEPORT = 386,        /* VAR_SO_REUSEPORT  */
    VAR_HARDEN_BELOW_NXDOMAIN = 387, /* VAR_HARDEN_BELOW_NXDOMAIN  */
    VAR_IGNORE_CD_FLAG = 388,      /* VAR_IGNORE_CD_FLAG  */
    VAR_LOG_QUERIES = 389,         /* VAR_LOG_QUERIES  */
    VAR_LOG_REPLIES = 390,         /* VAR_LOG_REPLIES  */
    VAR_LOG_LOCAL_ACTIONS = 391,   /* VAR_LOG_LOCAL_ACTIONS  */
    VAR_TCP_UPSTREAM = 392,        /* VAR_TCP_UPSTREAM  */
    VAR_SSL_UPSTREAM = 393,        /* VAR_SSL_UPSTREAM  */
    VAR_TCP_AUTH_QUERY_TIMEOUT = 394, /* VAR_TCP_AUTH_QUERY_TIMEOUT  */
    VAR_SSL_SERVICE_KEY = 395,     /* VAR_SSL_SERVICE_KEY  */
    VAR_SSL_SERVICE_PEM = 396,     /* VAR_SSL_SERVICE_PEM  */
    VAR_SSL_PORT = 397,            /* VAR_SSL_PORT  */
    VAR_FORWARD_FIRST = 398,       /* VAR_FORWARD_FIRST  */
    VAR_STUB_SSL_UPSTREAM = 399,   /* VAR_STUB_SSL_UPSTREAM  */
    VAR_FORWARD_SSL_UPSTREAM = 400, /* VAR_FORWARD_SSL_UPSTREAM  */
    VAR_TLS_CERT_BUNDLE = 401,     /* VAR_TLS_CERT_BUNDLE  */
    VAR_STUB_TCP_UPSTREAM = 402,   /* VAR_STUB_TCP_UPSTREAM  */
    VAR_FORWARD_TCP_UPSTREAM = 403, /* VAR_FORWARD_TCP_UPSTREAM  */
    VAR_HTTPS_PORT = 404,          /* VAR_HTTPS_PORT  */
    VAR_HTTP_ENDPOINT = 405,       /* VAR_HTTP_ENDPOINT  */
    VAR_HTTP_MAX_STREAMS = 406,    /* VAR_HTTP_MAX_STREAMS  */
    VAR_HTTP_QUERY_BUFFER_SIZE = 407, /* VAR_HTTP_QUERY_BUFFER_SIZE  */
    VAR_HTTP_RESPONSE_BUFFER_SIZE = 408, /* VAR_HTTP_RESPONSE_BUFFER_SIZE  */
    VAR_HTTP_NODELAY = 409,        /* VAR_HTTP_NODELAY  */
    VAR_HTTP_NOTLS_DOWNSTREAM = 410, /* VAR_HTTP_NOTLS_DOWNSTREAM  */
    VAR_STUB_FIRST = 411,          /* VAR_STUB_FIRST  */
    VAR_MINIMAL_RESPONSES = 412,   /* VAR_MINIMAL_RESPONSES  */
    VAR_RRSET_ROUNDROBIN = 413,    /* VAR_RRSET_ROUNDROBIN  */
    VAR_MAX_UDP_SIZE = 414,        /* VAR_MAX_UDP_SIZE  */
    VAR_DELAY_CLOSE = 415,         /* VAR_DELAY_CLOSE  */
    VAR_UDP_CONNECT = 416,         /* VAR_UDP_CONNECT  */
    VAR_UNBLOCK_LAN_ZONES = 417,   /* VAR_UNBLOCK_LAN_ZONES  */
    VAR_INSECURE_LAN_ZONES = 418,  /* VAR_INSECURE_LAN_ZONES  */
    VAR_INFRA_CACHE_MIN_RTT = 419, /* VAR_INFRA_CACHE_MIN_RTT  */
    VAR_INFRA_CACHE_MAX_RTT = 420, /* VAR_INFRA_CACHE_MAX_RTT  */
    VAR_INFRA_KEEP_PROBING = 421,  /* VAR_INFRA_KEEP_PROBING  */
    VAR_DNS64_PREFIX = 422,        /* VAR_DNS64_PREFIX  */
    VAR_DNS64_SYNTHALL = 423,      /* VAR_DNS64_SYNTHALL  */
    VAR_DNS64_IGNORE_AAAA = 424,   /* VAR_DNS64_IGNORE_AAAA  */
    VAR_DNSTAP = 425,              /* VAR_DNSTAP  */
    VAR_DNSTAP_ENABLE = 426,       /* VAR_DNSTAP_ENABLE  */
    VAR_DNSTAP_SOCKET_PATH = 427,  /* VAR_DNSTAP_SOCKET_PATH  */
    VAR_DNSTAP_IP = 428,           /* VAR_DNSTAP_IP  */
    VAR_DNSTAP_TLS = 429,          /* VAR_DNSTAP_TLS  */
    VAR_DNSTAP_TLS_SERVER_NAME = 430, /* VAR_DNSTAP_TLS_SERVER_NAME  */
    VAR_DNSTAP_TLS_CERT_BUNDLE = 431, /* VAR_DNSTAP_TLS_CERT_BUNDLE  */
    VAR_DNSTAP_TLS_CLIENT_KEY_FILE = 432, /* VAR_DNSTAP_TLS_CLIENT_KEY_FILE  */
    VAR_DNSTAP_TLS_CLIENT_CERT_FILE = 433, /* VAR_DNSTAP_TLS_CLIENT_CERT_FILE  */
    VAR_DNSTAP_SEND_IDENTITY = 434, /* VAR_DNSTAP_SEND_IDENTITY  */
    VAR_DNSTAP_SEND_VERSION = 435, /* VAR_DNSTAP_SEND_VERSION  */
    VAR_DNSTAP_BIDIRECTIONAL = 436, /* VAR_DNSTAP_BIDIRECTIONAL  */
    VAR_DNSTAP_IDENTITY = 437,     /* VAR_DNSTAP_IDENTITY  */
    VAR_DNSTAP_VERSION = 438,      /* VAR_DNSTAP_VERSION  */
    VAR_DNSTAP_LOG_RESOLVER_QUERY_MESSAGES = 439, /* VAR_DNSTAP_LOG_RESOLVER_QUERY_MESSAGES  */
    VAR_DNSTAP_LOG_RESOLVER_RESPONSE_MESSAGES = 440, /* VAR_DNSTAP_LOG_RESOLVER_RESPONSE_MESSAGES  */
    VAR_DNSTAP_LOG_CLIENT_QUERY_MESSAGES = 441, /* VAR_DNSTAP_LOG_CLIENT_QUERY_MESSAGES  */
    VAR_DNSTAP_LOG_CLIENT_RESPONSE_MESSAGES = 442, /* VAR_DNSTAP_LOG_CLIENT_RESPONSE_MESSAGES  */
    VAR_DNSTAP_LOG_FORWARDER_QUERY_MESSAGES = 443, /* VAR_DNSTAP_LOG_FORWARDER_QUERY_MESSAGES  */
    VAR_DNSTAP_LOG_FORWARDER_RESPONSE_MESSAGES = 444, /* VAR_DNSTAP_LOG_FORWARDER_RESPONSE_MESSAGES  */
    VAR_RESPONSE_IP_TAG = 445,     /* VAR_RESPONSE_IP_TAG  */
    VAR_RESPONSE_IP = 446,         /* VAR_RESPONSE_IP  */
    VAR_RESPONSE_IP_DATA = 447,    /* VAR_RESPONSE_IP_DATA  */
    VAR_HARDEN_ALGO_DOWNGRADE = 448, /* VAR_HARDEN_ALGO_DOWNGRADE  */
    VAR_IP_TRANSPARENT = 449,      /* VAR_IP_TRANSPARENT  */
    VAR_IP_DSCP = 450,             /* VAR_IP_DSCP  */
    VAR_DISABLE_DNSSEC_LAME_CHECK = 451, /* VAR_DISABLE_DNSSEC_LAME_CHECK  */
    VAR_IP_RATELIMIT = 452,        /* VAR_IP_RATELIMIT  */
    VAR_IP_RATELIMIT_SLABS = 453,  /* VAR_IP_RATELIMIT_SLABS  */
    VAR_IP_RATELIMIT_SIZE = 454,   /* VAR_IP_RATELIMIT_SIZE  */
    VAR_RATELIMIT = 455,           /* VAR_RATELIMIT  */
    VAR_RATELIMIT_SLABS = 456,     /* VAR_RATELIMIT_SLABS  */
    VAR_RATELIMIT_SIZE = 457,      /* VAR_RATELIMIT_SIZE  */
    VAR_OUTBOUND_MSG_RETRY = 458,  /* VAR_OUTBOUND_MSG_RETRY  */
    VAR_RATELIMIT_FOR_DOMAIN = 459, /* VAR_RATELIMIT_FOR_DOMAIN  */
    VAR_RATELIMIT_BELOW_DOMAIN = 460, /* VAR_RATELIMIT_BELOW_DOMAIN  */
    VAR_IP_RATELIMIT_FACTOR = 461, /* VAR_IP_RATELIMIT_FACTOR  */
    VAR_RATELIMIT_FACTOR = 462,    /* VAR_RATELIMIT_FACTOR  */
    VAR_IP_RATELIMIT_BACKOFF = 463, /* VAR_IP_RATELIMIT_BACKOFF  */
    VAR_RATELIMIT_BACKOFF = 464,   /* VAR_RATELIMIT_BACKOFF  */
    VAR_SEND_CLIENT_SUBNET = 465,  /* VAR_SEND_CLIENT_SUBNET  */
    VAR_CLIENT_SUBNET_ZONE = 466,  /* VAR_CLIENT_SUBNET_ZONE  */
    VAR_CLIENT_SUBNET_ALWAYS_FORWARD = 467, /* VAR_CLIENT_SUBNET_ALWAYS_FORWARD  */
    VAR_CLIENT_SUBNET_OPCODE = 468, /* VAR_CLIENT_SUBNET_OPCODE  */
    VAR_MAX_CLIENT_SUBNET_IPV4 = 469, /* VAR_MAX_CLIENT_SUBNET_IPV4  */
    VAR_MAX_CLIENT_SUBNET_IPV6 = 470, /* VAR_MAX_CLIENT_SUBNET_IPV6  */
    VAR_MIN_CLIENT_SUBNET_IPV4 = 471, /* VAR_MIN_CLIENT_SUBNET_IPV4  */
    VAR_MIN_CLIENT_SUBNET_IPV6 = 472, /* VAR_MIN_CLIENT_SUBNET_IPV6  */
    VAR_MAX_ECS_TREE_SIZE_IPV4 = 473, /* VAR_MAX_ECS_TREE_SIZE_IPV4  */
    VAR_MAX_ECS_TREE_SIZE_IPV6 = 474, /* VAR_MAX_ECS_TREE_SIZE_IPV6  */
    VAR_CAPS_WHITELIST = 475,      /* VAR_CAPS_WHITELIST  */
    VAR_CACHE_MAX_NEGATIVE_TTL = 476, /* VAR_CACHE_MAX_NEGATIVE_TTL  */
    VAR_PERMIT_SMALL_HOLDDOWN = 477, /* VAR_PERMIT_SMALL_HOLDDOWN  */
    VAR_QNAME_MINIMISATION = 478,  /* VAR_QNAME_MINIMISATION  */
    VAR_QNAME_MINIMISATION_STRICT = 479, /* VAR_QNAME_MINIMISATION_STRICT  */
    VAR_IP_FREEBIND = 480,         /* VAR_IP_FREEBIND  */
    VAR_DEFINE_TAG = 481,          /* VAR_DEFINE_TAG  */
    VAR_LOCAL_ZONE_TAG = 482,      /* VAR_LOCAL_ZONE_TAG  */
    VAR_ACCESS_CONTROL_TAG = 483,  /* VAR_ACCESS_CONTROL_TAG  */
    VAR_LOCAL_ZONE_OVERRIDE = 484, /* VAR_LOCAL_ZONE_OVERRIDE  */
    VAR_ACCESS_CONTROL_TAG_ACTION = 485, /* VAR_ACCESS_CONTROL_TAG_ACTION  */
    VAR_ACCESS_CONTROL_TAG_DATA = 486, /* VAR_ACCESS_CONTROL_TAG_DATA  */
    VAR_VIEW = 487,                /* VAR_VIEW  */
    VAR_ACCESS_CONTROL_VIEW = 488, /* VAR_ACCESS_CONTROL_VIEW  */
    VAR_VIEW_FIRST = 489,          /* VAR_VIEW_FIRST  */
    VAR_SERVE_EXPIRED = 490,       /* VAR_SERVE_EXPIRED  */
    VAR_SERVE_EXPIRED_TTL = 491,   /* VAR_SERVE_EXPIRED_TTL  */
    VAR_SERVE_EXPIRED_TTL_RESET = 492, /* VAR_SERVE_EXPIRED_TTL_RESET  */
    VAR_SERVE_EXPIRED_REPLY_TTL = 493, /* VAR_SERVE_EXPIRED_REPLY_TTL  */
    VAR_SERVE_EXPIRED_CLIENT_TIMEOUT = 494, /* VAR_SERVE_EXPIRED_CLIENT_TIMEOUT  */
    VAR_EDE_SERVE_EXPIRED = 495,   /* VAR_EDE_SERVE_EXPIRED  */
    VAR_SERVE_ORIGINAL_TTL = 496,  /* VAR_SERVE_ORIGINAL_TTL  */
    VAR_FAKE_DSA = 497,            /* VAR_FAKE_DSA  */
    VAR_FAKE_SHA1 = 498,           /* VAR_FAKE_SHA1  */
    VAR_LOG_IDENTITY = 499,        /* VAR_LOG_IDENTITY  */
    VAR_HIDE_TRUSTANCHOR = 500,    /* VAR_HIDE_TRUSTANCHOR  */
    VAR_HIDE_HTTP_USER_AGENT = 501, /* VAR_HIDE_HTTP_USER_AGENT  */
    VAR_HTTP_USER_AGENT = 502,     /* VAR_HTTP_USER_AGENT  */
    VAR_TRUST_ANCHOR_SIGNALING = 503, /* VAR_TRUST_ANCHOR_SIGNALING  */
    VAR_AGGRESSIVE_NSEC = 504,     /* VAR_AGGRESSIVE_NSEC  */
    VAR_USE_SYSTEMD = 505,         /* VAR_USE_SYSTEMD  */
    VAR_SHM_ENABLE = 506,          /* VAR_SHM_ENABLE  */
    VAR_SHM_KEY = 507,             /* VAR_SHM_KEY  */
    VAR_ROOT_KEY_SENTINEL = 508,   /* VAR_ROOT_KEY_SENTINEL  */
    VAR_DNSCRYPT = 509,            /* VAR_DNSCRYPT  */
    VAR_DNSCRYPT_ENABLE = 510,     /* VAR_DNSCRYPT_ENABLE  */
    VAR_DNSCRYPT_PORT = 511,       /* VAR_DNSCRYPT_PORT  */
    VAR_DNSCRYPT_PROVIDER = 512,   /* VAR_DNSCRYPT_PROVIDER  */
    VAR_DNSCRYPT_SECRET_KEY = 513, /* VAR_DNSCRYPT_SECRET_KEY  */
    VAR_DNSCRYPT_PROVIDER_CERT = 514, /* VAR_DNSCRYPT_PROVIDER_CERT  */
    VAR_DNSCRYPT_PROVIDER_CERT_ROTATED = 515, /* VAR_DNSCRYPT_PROVIDER_CERT_ROTATED  */
    VAR_DNSCRYPT_SHARED_SECRET_CACHE_SIZE = 516, /* VAR_DNSCRYPT_SHARED_SECRET_CACHE_SIZE  */
    VAR_DNSCRYPT_SHARED_SECRET_CACHE_SLABS = 517, /* VAR_DNSCRYPT_SHARED_SECRET_CACHE_SLABS  */
    VAR_DNSCRYPT_NONCE_CACHE_SIZE = 518, /* VAR_DNSCRYPT_NONCE_CACHE_SIZE  */
    VAR_DNSCRYPT_NONCE_CACHE_SLABS = 519, /* VAR_DNSCRYPT_NONCE_CACHE_SLABS  */
    VAR_PAD_RESPONSES = 520,       /* VAR_PAD_RESPONSES  */
    VAR_PAD_RESPONSES_BLOCK_SIZE = 521, /* VAR_PAD_RESPONSES_BLOCK_SIZE  */
    VAR_PAD_QUERIES = 522,         /* VAR_PAD_QUERIES  */
    VAR_PAD_QUERIES_BLOCK_SIZE = 523, /* VAR_PAD_QUERIES_BLOCK_SIZE  */
    VAR_IPSECMOD_ENABLED = 524,    /* VAR_IPSECMOD_ENABLED  */
    VAR_IPSECMOD_HOOK = 525,       /* VAR_IPSECMOD_HOOK  */
    VAR_IPSECMOD_IGNORE_BOGUS = 526, /* VAR_IPSECMOD_IGNORE_BOGUS  */
    VAR_IPSECMOD_MAX_TTL = 527,    /* VAR_IPSECMOD_MAX_TTL  */
    VAR_IPSECMOD_WHITELIST = 528,  /* VAR_IPSECMOD_WHITELIST  */
    VAR_IPSECMOD_STRICT = 529,     /* VAR_IPSECMOD_STRICT  */
    VAR_CACHEDB = 530,             /* VAR_CACHEDB  */
    VAR_CACHEDB_BACKEND = 531,     /* VAR_CACHEDB_BACKEND  */
    VAR_CACHEDB_SECRETSEED = 532,  /* VAR_CACHEDB_SECRETSEED  */
    VAR_CACHEDB_REDISHOST = 533,   /* VAR_CACHEDB_REDISHOST  */
    VAR_CACHEDB_REDISPORT = 534,   /* VAR_CACHEDB_REDISPORT  */
    VAR_CACHEDB_REDISTIMEOUT = 535, /* VAR_CACHEDB_REDISTIMEOUT  */
    VAR_CACHEDB_REDISEXPIRERECORDS = 536, /* VAR_CACHEDB_REDISEXPIRERECORDS  */
    VAR_UDP_UPSTREAM_WITHOUT_DOWNSTREAM = 537, /* VAR_UDP_UPSTREAM_WITHOUT_DOWNSTREAM  */
    VAR_FOR_UPSTREAM = 538,        /* VAR_FOR_UPSTREAM  */
    VAR_AUTH_ZONE = 539,           /* VAR_AUTH_ZONE  */
    VAR_ZONEFILE = 540,            /* VAR_ZONEFILE  */
    VAR_MASTER = 541,              /* VAR_MASTER  */
    VAR_URL = 542,                 /* VAR_URL  */
    VAR_FOR_DOWNSTREAM = 543,      /* VAR_FOR_DOWNSTREAM  */
    VAR_FALLBACK_ENABLED = 544,    /* VAR_FALLBACK_ENABLED  */
    VAR_TLS_ADDITIONAL_PORT = 545, /* VAR_TLS_ADDITIONAL_PORT  */
    VAR_LOW_RTT = 546,             /* VAR_LOW_RTT  */
    VAR_LOW_RTT_PERMIL = 547,      /* VAR_LOW_RTT_PERMIL  */
    VAR_FAST_SERVER_PERMIL = 548,  /* VAR_FAST_SERVER_PERMIL  */
    VAR_FAST_SERVER_NUM = 549,     /* VAR_FAST_SERVER_NUM  */
    VAR_ALLOW_NOTIFY = 550,        /* VAR_ALLOW_NOTIFY  */
    VAR_TLS_WIN_CERT = 551,        /* VAR_TLS_WIN_CERT  */
    VAR_TCP_CONNECTION_LIMIT = 552, /* VAR_TCP_CONNECTION_LIMIT  */
    VAR_FORWARD_NO_CACHE = 553,    /* VAR_FORWARD_NO_CACHE  */
    VAR_STUB_NO_CACHE = 554,       /* VAR_STUB_NO_CACHE  */
    VAR_LOG_SERVFAIL = 555,        /* VAR_LOG_SERVFAIL  */
    VAR_DENY_ANY = 556,            /* VAR_DENY_ANY  */
    VAR_UNKNOWN_SERVER_TIME_LIMIT = 557, /* VAR_UNKNOWN_SERVER_TIME_LIMIT  */
    VAR_LOG_TAG_QUERYREPLY = 558,  /* VAR_LOG_TAG_QUERYREPLY  */
    VAR_STREAM_WAIT_SIZE = 559,    /* VAR_STREAM_WAIT_SIZE  */
    VAR_TLS_CIPHERS = 560,         /* VAR_TLS_CIPHERS  */
    VAR_TLS_CIPHERSUITES = 561,    /* VAR_TLS_CIPHERSUITES  */
    VAR_TLS_USE_SNI = 562,         /* VAR_TLS_USE_SNI  */
    VAR_IPSET = 563,               /* VAR_IPSET  */
    VAR_IPSET_NAME_V4 = 564,       /* VAR_IPSET_NAME_V4  */
    VAR_IPSET_NAME_V6 = 565,       /* VAR_IPSET_NAME_V6  */
    VAR_TLS_SESSION_TICKET_KEYS = 566, /* VAR_TLS_SESSION_TICKET_KEYS  */
    VAR_RPZ = 567,                 /* VAR_RPZ  */
    VAR_TAGS = 568,                /* VAR_TAGS  */
    VAR_RPZ_ACTION_OVERRIDE = 569, /* VAR_RPZ_ACTION_OVERRIDE  */
    VAR_RPZ_CNAME_OVERRIDE = 570,  /* VAR_RPZ_CNAME_OVERRIDE  */
    VAR_RPZ_LOG = 571,             /* VAR_RPZ_LOG  */
    VAR_RPZ_LOG_NAME = 572,        /* VAR_RPZ_LOG_NAME  */
    VAR_DYNLIB = 573,              /* VAR_DYNLIB  */
    VAR_DYNLIB_FILE = 574,         /* VAR_DYNLIB_FILE  */
    VAR_EDNS_CLIENT_STRING = 575,  /* VAR_EDNS_CLIENT_STRING  */
    VAR_EDNS_CLIENT_STRING_OPCODE = 576, /* VAR_EDNS_CLIENT_STRING_OPCODE  */
    VAR_NSID = 577,                /* VAR_NSID  */
    VAR_ZONEMD_PERMISSIVE_MODE = 578, /* VAR_ZONEMD_PERMISSIVE_MODE  */
    VAR_ZONEMD_CHECK = 579,        /* VAR_ZONEMD_CHECK  */
    VAR_ZONEMD_REJECT_ABSENCE = 580, /* VAR_ZONEMD_REJECT_ABSENCE  */
    VAR_RPZ_SIGNAL_NXDOMAIN_RA = 581, /* VAR_RPZ_SIGNAL_NXDOMAIN_RA  */
    VAR_INTERFACE_AUTOMATIC_PORTS = 582, /* VAR_INTERFACE_AUTOMATIC_PORTS  */
    VAR_EDE = 583,                 /* VAR_EDE  */
    VAR_INTERFACE_ACTION = 584,    /* VAR_INTERFACE_ACTION  */
    VAR_INTERFACE_VIEW = 585,      /* VAR_INTERFACE_VIEW  */
    VAR_INTERFACE_TAG = 586,       /* VAR_INTERFACE_TAG  */
    VAR_INTERFACE_TAG_ACTION = 587, /* VAR_INTERFACE_TAG_ACTION  */
    VAR_INTERFACE_TAG_DATA = 588,  /* VAR_INTERFACE_TAG_DATA  */
    VAR_PROXY_PROTOCOL_PORT = 589  /* VAR_PROXY_PROTOCOL_PORT  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif
/* Token kinds.  */
#define YYEMPTY -2
#define YYEOF 0
#define YYerror 256
#define YYUNDEF 257
#define SPACE 258
#define LETTER 259
#define NEWLINE 260
#define COMMENT 261
#define COLON 262
#define ANY 263
#define ZONESTR 264
#define STRING_ARG 265
#define VAR_FORCE_TOPLEVEL 266
#define VAR_SERVER 267
#define VAR_VERBOSITY 268
#define VAR_NUM_THREADS 269
#define VAR_PORT 270
#define VAR_OUTGOING_RANGE 271
#define VAR_INTERFACE 272
#define VAR_PREFER_IP4 273
#define VAR_DO_IP4 274
#define VAR_DO_IP6 275
#define VAR_PREFER_IP6 276
#define VAR_DO_UDP 277
#define VAR_DO_TCP 278
#define VAR_TCP_MSS 279
#define VAR_OUTGOING_TCP_MSS 280
#define VAR_TCP_IDLE_TIMEOUT 281
#define VAR_EDNS_TCP_KEEPALIVE 282
#define VAR_EDNS_TCP_KEEPALIVE_TIMEOUT 283
#define VAR_CHROOT 284
#define VAR_USERNAME 285
#define VAR_DIRECTORY 286
#define VAR_LOGFILE 287
#define VAR_PIDFILE 288
#define VAR_AZONE_IO_THREAD 289
#define VAR_MSG_CACHE_SIZE 290
#define VAR_MSG_CACHE_SLABS 291
#define VAR_NUM_QUERIES_PER_THREAD 292
#define VAR_RRSET_CACHE_SIZE 293
#define VAR_RRSET_CACHE_SLABS 294
#define VAR_OUTGOING_NUM_TCP 295
#define VAR_INFRA_HOST_TTL 296
#define VAR_INFRA_LAME_TTL 297
#define VAR_INFRA_CACHE_SLABS 298
#define VAR_INFRA_CACHE_NUMHOSTS 299
#define VAR_INFRA_CACHE_LAME_SIZE 300
#define VAR_NAME 301
#define VAR_STUB_ZONE 302
#define VAR_STUB_HOST 303
#define VAR_STUB_ADDR 304
#define VAR_TARGET_FETCH_POLICY 305
#define VAR_HARDEN_SHORT_BUFSIZE 306
#define VAR_HARDEN_LARGE_QUERIES 307
#define VAR_FORWARD_ZONE 308
#define VAR_FORWARD_HOST 309
#define VAR_FORWARD_ADDR 310
#define VAR_DO_NOT_QUERY_ADDRESS 311
#define VAR_HIDE_IDENTITY 312
#define VAR_HIDE_VERSION 313
#define VAR_IDENTITY 314
#define VAR_VERSION 315
#define VAR_HARDEN_GLUE 316
#define VAR_MODULE_CONF 317
#define VAR_TRUST_ANCHOR_FILE 318
#define VAR_TRUST_ANCHOR 319
#define VAR_VAL_OVERRIDE_DATE 320
#define VAR_BOGUS_TTL 321
#define VAR_VAL_CLEAN_ADDITIONAL 322
#define VAR_VAL_PERMISSIVE_MODE 323
#define VAR_INCOMING_NUM_TCP 324
#define VAR_MSG_BUFFER_SIZE 325
#define VAR_KEY_CACHE_SIZE 326
#define VAR_KEY_CACHE_SLABS 327
#define VAR_TRUSTED_KEYS_FILE 328
#define VAR_VAL_NSEC3_KEYSIZE_ITERATIONS 329
#define VAR_USE_SYSLOG 330
#define VAR_OUTGOING_INTERFACE 331
#define VAR_ROOT_HINTS 332
#define VAR_DO_NOT_QUERY_LOCALHOST 333
#define VAR_CACHE_MAX_TTL 334
#define VAR_HARDEN_DNSSEC_STRIPPED 335
#define VAR_ACCESS_CONTROL 336
#define VAR_LOCAL_ZONE 337
#define VAR_LOCAL_DATA 338
#define VAR_INTERFACE_AUTOMATIC 339
#define VAR_STATISTICS_INTERVAL 340
#define VAR_DO_DAEMONIZE 341
#define VAR_USE_CAPS_FOR_ID 342
#define VAR_STATISTICS_CUMULATIVE 343
#define VAR_OUTGOING_PORT_PERMIT 344
#define VAR_OUTGOING_PORT_AVOID 345
#define VAR_DLV_ANCHOR_FILE 346
#define VAR_DLV_ANCHOR 347
#define VAR_NEG_CACHE_SIZE 348
#define VAR_HARDEN_REFERRAL_PATH 349
#define VAR_PRIVATE_ADDRESS 350
#define VAR_PRIVATE_DOMAIN 351
#define VAR_REMOTE_CONTROL 352
#define VAR_CONTROL_ENABLE 353
#define VAR_CONTROL_INTERFACE 354
#define VAR_CONTROL_PORT 355
#define VAR_SERVER_KEY_FILE 356
#define VAR_SERVER_CERT_FILE 357
#define VAR_CONTROL_KEY_FILE 358
#define VAR_CONTROL_CERT_FILE 359
#define VAR_CONTROL_USE_CERT 360
#define VAR_TCP_REUSE_TIMEOUT 361
#define VAR_MAX_REUSE_TCP_QUERIES 362
#define VAR_EXTENDED_STATISTICS 363
#define VAR_LOCAL_DATA_PTR 364
#define VAR_JOSTLE_TIMEOUT 365
#define VAR_STUB_PRIME 366
#define VAR_UNWANTED_REPLY_THRESHOLD 367
#define VAR_LOG_TIME_ASCII 368
#define VAR_DOMAIN_INSECURE 369
#define VAR_PYTHON 370
#define VAR_PYTHON_SCRIPT 371
#define VAR_VAL_SIG_SKEW_MIN 372
#define VAR_VAL_SIG_SKEW_MAX 373
#define VAR_VAL_MAX_RESTART 374
#define VAR_CACHE_MIN_TTL 375
#define VAR_VAL_LOG_LEVEL 376
#define VAR_AUTO_TRUST_ANCHOR_FILE 377
#define VAR_KEEP_MISSING 378
#define VAR_ADD_HOLDDOWN 379
#define VAR_DEL_HOLDDOWN 380
#define VAR_SO_RCVBUF 381
#define VAR_EDNS_BUFFER_SIZE 382
#define VAR_PREFETCH 383
#define VAR_PREFETCH_KEY 384
#define VAR_SO_SNDBUF 385
#define VAR_SO_REUSEPORT 386
#define VAR_HARDEN_BELOW_NXDOMAIN 387
#define VAR_IGNORE_CD_FLAG 388
#define VAR_LOG_QUERIES 389
#define VAR_LOG_REPLIES 390
#define VAR_LOG_LOCAL_ACTIONS 391
#define VAR_TCP_UPSTREAM 392
#define VAR_SSL_UPSTREAM 393
#define VAR_TCP_AUTH_QUERY_TIMEOUT 394
#define VAR_SSL_SERVICE_KEY 395
#define VAR_SSL_SERVICE_PEM 396
#define VAR_SSL_PORT 397
#define VAR_FORWARD_FIRST 398
#define VAR_STUB_SSL_UPSTREAM 399
#define VAR_FORWARD_SSL_UPSTREAM 400
#define VAR_TLS_CERT_BUNDLE 401
#define VAR_STUB_TCP_UPSTREAM 402
#define VAR_FORWARD_TCP_UPSTREAM 403
#define VAR_HTTPS_PORT 404
#define VAR_HTTP_ENDPOINT 405
#define VAR_HTTP_MAX_STREAMS 406
#define VAR_HTTP_QUERY_BUFFER_SIZE 407
#define VAR_HTTP_RESPONSE_BUFFER_SIZE 408
#define VAR_HTTP_NODELAY 409
#define VAR_HTTP_NOTLS_DOWNSTREAM 410
#define VAR_STUB_FIRST 411
#define VAR_MINIMAL_RESPONSES 412
#define VAR_RRSET_ROUNDROBIN 413
#define VAR_MAX_UDP_SIZE 414
#define VAR_DELAY_CLOSE 415
#define VAR_UDP_CONNECT 416
#define VAR_UNBLOCK_LAN_ZONES 417
#define VAR_INSECURE_LAN_ZONES 418
#define VAR_INFRA_CACHE_MIN_RTT 419
#define VAR_INFRA_CACHE_MAX_RTT 420
#define VAR_INFRA_KEEP_PROBING 421
#define VAR_DNS64_PREFIX 422
#define VAR_DNS64_SYNTHALL 423
#define VAR_DNS64_IGNORE_AAAA 424
#define VAR_DNSTAP 425
#define VAR_DNSTAP_ENABLE 426
#define VAR_DNSTAP_SOCKET_PATH 427
#define VAR_DNSTAP_IP 428
#define VAR_DNSTAP_TLS 429
#define VAR_DNSTAP_TLS_SERVER_NAME 430
#define VAR_DNSTAP_TLS_CERT_BUNDLE 431
#define VAR_DNSTAP_TLS_CLIENT_KEY_FILE 432
#define VAR_DNSTAP_TLS_CLIENT_CERT_FILE 433
#define VAR_DNSTAP_SEND_IDENTITY 434
#define VAR_DNSTAP_SEND_VERSION 435
#define VAR_DNSTAP_BIDIRECTIONAL 436
#define VAR_DNSTAP_IDENTITY 437
#define VAR_DNSTAP_VERSION 438
#define VAR_DNSTAP_LOG_RESOLVER_QUERY_MESSAGES 439
#define VAR_DNSTAP_LOG_RESOLVER_RESPONSE_MESSAGES 440
#define VAR_DNSTAP_LOG_CLIENT_QUERY_MESSAGES 441
#define VAR_DNSTAP_LOG_CLIENT_RESPONSE_MESSAGES 442
#define VAR_DNSTAP_LOG_FORWARDER_QUERY_MESSAGES 443
#define VAR_DNSTAP_LOG_FORWARDER_RESPONSE_MESSAGES 444
#define VAR_RESPONSE_IP_TAG 445
#define VAR_RESPONSE_IP 446
#define VAR_RESPONSE_IP_DATA 447
#define VAR_HARDEN_ALGO_DOWNGRADE 448
#define VAR_IP_TRANSPARENT 449
#define VAR_IP_DSCP 450
#define VAR_DISABLE_DNSSEC_LAME_CHECK 451
#define VAR_IP_RATELIMIT 452
#define VAR_IP_RATELIMIT_SLABS 453
#define VAR_IP_RATELIMIT_SIZE 454
#define VAR_RATELIMIT 455
#define VAR_RATELIMIT_SLABS 456
#define VAR_RATELIMIT_SIZE 457
#define VAR_OUTBOUND_MSG_RETRY 458
#define VAR_RATELIMIT_FOR_DOMAIN 459
#define VAR_RATELIMIT_BELOW_DOMAIN 460
#define VAR_IP_RATELIMIT_FACTOR 461
#define VAR_RATELIMIT_FACTOR 462
#define VAR_IP_RATELIMIT_BACKOFF 463
#define VAR_RATELIMIT_BACKOFF 464
#define VAR_SEND_CLIENT_SUBNET 465
#define VAR_CLIENT_SUBNET_ZONE 466
#define VAR_CLIENT_SUBNET_ALWAYS_FORWARD 467
#define VAR_CLIENT_SUBNET_OPCODE 468
#define VAR_MAX_CLIENT_SUBNET_IPV4 469
#define VAR_MAX_CLIENT_SUBNET_IPV6 470
#define VAR_MIN_CLIENT_SUBNET_IPV4 471
#define VAR_MIN_CLIENT_SUBNET_IPV6 472
#define VAR_MAX_ECS_TREE_SIZE_IPV4 473
#define VAR_MAX_ECS_TREE_SIZE_IPV6 474
#define VAR_CAPS_WHITELIST 475
#define VAR_CACHE_MAX_NEGATIVE_TTL 476
#define VAR_PERMIT_SMALL_HOLDDOWN 477
#define VAR_QNAME_MINIMISATION 478
#define VAR_QNAME_MINIMISATION_STRICT 479
#define VAR_IP_FREEBIND 480
#define VAR_DEFINE_TAG 481
#define VAR_LOCAL_ZONE_TAG 482
#define VAR_ACCESS_CONTROL_TAG 483
#define VAR_LOCAL_ZONE_OVERRIDE 484
#define VAR_ACCESS_CONTROL_TAG_ACTION 485
#define VAR_ACCESS_CONTROL_TAG_DATA 486
#define VAR_VIEW 487
#define VAR_ACCESS_CONTROL_VIEW 488
#define VAR_VIEW_FIRST 489
#define VAR_SERVE_EXPIRED 490
#define VAR_SERVE_EXPIRED_TTL 491
#define VAR_SERVE_EXPIRED_TTL_RESET 492
#define VAR_SERVE_EXPIRED_REPLY_TTL 493
#define VAR_SERVE_EXPIRED_CLIENT_TIMEOUT 494
#define VAR_EDE_SERVE_EXPIRED 495
#define VAR_SERVE_ORIGINAL_TTL 496
#define VAR_FAKE_DSA 497
#define VAR_FAKE_SHA1 498
#define VAR_LOG_IDENTITY 499
#define VAR_HIDE_TRUSTANCHOR 500
#define VAR_HIDE_HTTP_USER_AGENT 501
#define VAR_HTTP_USER_AGENT 502
#define VAR_TRUST_ANCHOR_SIGNALING 503
#define VAR_AGGRESSIVE_NSEC 504
#define VAR_USE_SYSTEMD 505
#define VAR_SHM_ENABLE 506
#define VAR_SHM_KEY 507
#define VAR_ROOT_KEY_SENTINEL 508
#define VAR_DNSCRYPT 509
#define VAR_DNSCRYPT_ENABLE 510
#define VAR_DNSCRYPT_PORT 511
#define VAR_DNSCRYPT_PROVIDER 512
#define VAR_DNSCRYPT_SECRET_KEY 513
#define VAR_DNSCRYPT_PROVIDER_CERT 514
#define VAR_DNSCRYPT_PROVIDER_CERT_ROTATED 515
#define VAR_DNSCRYPT_SHARED_SECRET_CACHE_SIZE 516
#define VAR_DNSCRYPT_SHARED_SECRET_CACHE_SLABS 517
#define VAR_DNSCRYPT_NONCE_CACHE_SIZE 518
#define VAR_DNSCRYPT_NONCE_CACHE_SLABS 519
#define VAR_PAD_RESPONSES 520
#define VAR_PAD_RESPONSES_BLOCK_SIZE 521
#define VAR_PAD_QUERIES 522
#define VAR_PAD_QUERIES_BLOCK_SIZE 523
#define VAR_IPSECMOD_ENABLED 524
#define VAR_IPSECMOD_HOOK 525
#define VAR_IPSECMOD_IGNORE_BOGUS 526
#define VAR_IPSECMOD_MAX_TTL 527
#define VAR_IPSECMOD_WHITELIST 528
#define VAR_IPSECMOD_STRICT 529
#define VAR_CACHEDB 530
#define VAR_CACHEDB_BACKEND 531
#define VAR_CACHEDB_SECRETSEED 532
#define VAR_CACHEDB_REDISHOST 533
#define VAR_CACHEDB_REDISPORT 534
#define VAR_CACHEDB_REDISTIMEOUT 535
#define VAR_CACHEDB_REDISEXPIRERECORDS 536
#define VAR_UDP_UPSTREAM_WITHOUT_DOWNSTREAM 537
#define VAR_FOR_UPSTREAM 538
#define VAR_AUTH_ZONE 539
#define VAR_ZONEFILE 540
#define VAR_MASTER 541
#define VAR_URL 542
#define VAR_FOR_DOWNSTREAM 543
#define VAR_FALLBACK_ENABLED 544
#define VAR_TLS_ADDITIONAL_PORT 545
#define VAR_LOW_RTT 546
#define VAR_LOW_RTT_PERMIL 547
#define VAR_FAST_SERVER_PERMIL 548
#define VAR_FAST_SERVER_NUM 549
#define VAR_ALLOW_NOTIFY 550
#define VAR_TLS_WIN_CERT 551
#define VAR_TCP_CONNECTION_LIMIT 552
#define VAR_FORWARD_NO_CACHE 553
#define VAR_STUB_NO_CACHE 554
#define VAR_LOG_SERVFAIL 555
#define VAR_DENY_ANY 556
#define VAR_UNKNOWN_SERVER_TIME_LIMIT 557
#define VAR_LOG_TAG_QUERYREPLY 558
#define VAR_STREAM_WAIT_SIZE 559
#define VAR_TLS_CIPHERS 560
#define VAR_TLS_CIPHERSUITES 561
#define VAR_TLS_USE_SNI 562
#define VAR_IPSET 563
#define VAR_IPSET_NAME_V4 564
#define VAR_IPSET_NAME_V6 565
#define VAR_TLS_SESSION_TICKET_KEYS 566
#define VAR_RPZ 567
#define VAR_TAGS 568
#define VAR_RPZ_ACTION_OVERRIDE 569
#define VAR_RPZ_CNAME_OVERRIDE 570
#define VAR_RPZ_LOG 571
#define VAR_RPZ_LOG_NAME 572
#define VAR_DYNLIB 573
#define VAR_DYNLIB_FILE 574
#define VAR_EDNS_CLIENT_STRING 575
#define VAR_EDNS_CLIENT_STRING_OPCODE 576
#define VAR_NSID 577
#define VAR_ZONEMD_PERMISSIVE_MODE 578
#define VAR_ZONEMD_CHECK 579
#define VAR_ZONEMD_REJECT_ABSENCE 580
#define VAR_RPZ_SIGNAL_NXDOMAIN_RA 581
#define VAR_INTERFACE_AUTOMATIC_PORTS 582
#define VAR_EDE 583
#define VAR_INTERFACE_ACTION 584
#define VAR_INTERFACE_VIEW 585
#define VAR_INTERFACE_TAG 586
#define VAR_INTERFACE_TAG_ACTION 587
#define VAR_INTERFACE_TAG_DATA 588
#define VAR_PROXY_PROTOCOL_PORT 589

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
union YYSTYPE
{
#line 67 "./util/configparser.y"

	char*	str;

#line 739 "util/configparser.h"

};
typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;


int yyparse (void);


#endif /* !YY_YY_UTIL_CONFIGPARSER_H_INCLUDED  */
