name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: false
    - name: install packages
      run: sudo apt-get install autoconf automake libtool make
    - name: configure
      run: |
        autoreconf -fi
        ./configure --enable-debug
    - name: make
      run: make
    - name: make test
      run: make test
